# render.yaml — Despliegue automático en Render
services:
  - type: web
    name: aemet-avisos-zona              # <- puedes cambiarlo si quieres
    env: node
    region: frankfurt                    # UE (baja latencia desde ES)
    plan: free                           # cambia a starter/standard si lo necesitas
    autoDeploy: true

    buildCommand: npm install --omit=dev # <-- arregla el error por falta de package-lock.json
    startCommand: node server.js
    healthCheckPath: /health

    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: AEMET_API_KEY               # <<< más seguro vía Secret en Render
        fromSecret: aemet-api-key
