services:
  - type: web
    name: aemet-avisos-zona
    env: node
    region: frankfurt
    plan: free
    autoDeploy: true
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: AEMET_API_KEY
        fromSecret: aemet-api-key   # crea este Secret en Render con tu api_key
